trigger:
  - none

pr: 
  - main

pool:
  name: "DAS-SGLA"

resources:
  repositories:
    - repository: agronext_workflows
      type: git
      name: workflows

jobs:
  - template: integration.yml@workflows
    parameters:
      package_path: './agronext_api'