trigger:
  - none

pr: 
  - main

pool:
  name: "DAS-SGLA"

resources:
  repositories:
    - repository: workflows
      type: git
      name: agronext_workflows

jobs:
  - template: integration.yml@workflows
    parameters:
      package_path: './agronext_api'