trigger:
  - none

pr: 
  branches:
    include:
      - main
      - development
  paths:
    exclude:
      - './workflows/**'

pool:
  name: "DAS-SGLA"

resources:
  repositories:
    - repository: workflows
      type: git
      name: agronext_workflows

variables:
  - group: Credentials

stages:
  - stage: Publish
    displayName: Publish Package
    jobs:
      - template: publish.yml@workflows
        parameters:
          package_path: './agronext_api'

  - Stage: Trigger Dependents to Bump Version
    dependsOn: Publish
    condition: succeeded()
    jobs:
      - job: Bump Dependents
        displayName: Trigger Dependent
        strategy:
          matrix:
            acquisition_service:
              service_path: 'agronext_service'
            support_service:
              service_path: 'support_service'
        steps:
          - script: echo "Trigerring $(service_path)..."