def build_excluded_risks() -> str:
    # Excluded risks information
    excluded_risks_information = [
        "Conforme Cláusula 4 das Condições Gerais do Seguro:",
        "Por ser uma apólice ou certificado de seguro de riscos nomeados, se entende que não está coberto qualquer risco não descrito na Cláusula 3 nas presentes Condições Gerais. Não obstante, ao anterior, se especificam particularmente as seguintes exclusões:",
        "4.1- As perdas normais e/ou próprias do processo biológico de germinação da semente e do desenvolvimento da cultura segurada.",
        "4.2- As perdas e danos de qualquer natureza, que tenham afetado a cultura segurada antes do início ou após o final de vigência da presente apólice ou do certificado de seguro.",
        "4.3- As perdas ocasionadas por enfermidades, ervas daninhas ou pragas de qualquer tipo ou origem, ainda que utilizados métodos viáveis e existentes para seu controle.",
        "4.4- As perdas causadas por cataclismos tais como terremotos e erupções vulcânicas.",
        "4.5- Culturas destinadas para experimentação ou as perdas causadas por experimentos e/ou ensaios de qualquer natureza.",
        "4.6- As perdas causadas por aplicação deliberada ou involuntária de produtos químicos não específicos, não registrados ou não recomendados em quantidade ou qualidade para a proteção da cultura segurada.",
        "4.7- As perdas causadas por aplicação deliberada ou involuntária de produtos químicos específicos, registrados para a proteção da cultura segurada, porém, em quantidades não recomendadas.",
        "4.8- As perdas causadas por ação direta de insetos, aves, animais domésticos ou animais silvestres.",
        "4.9- As perdas causadas por fogo ou ação do calor.",
        "4.10- Atos ilícitos dolosos ou por culpa grave equiparável ao dolo praticados pelo Segurado, pelos beneficiários do seguro ou de seus representantes leais, de cada uma destas partes. Se o Segurado for pessoa jurídica esta exclusão se aplicará aos sócios controladores da empresa segurada, aos dirigentes e administradores, aos beneficiários, e também aos representantes de cada uma dessas pessoas.",
        "4.11- As perdas ou danos causados por roubo ou furto do bem segurado.",
        "4.12- A eliminação ou destruição intencional ou confisco do bem segurado, quando seja ordenada ou efetuada pela autoridade competente que tenha jurisdição sobre a matéria.",
        "4.13- As perdas de receita de todo tipo, resultantes da suspensão permanente ou temporária da operação de produção agrícola, ainda que a causa material desta tenha sido indenizada; assim como obrigações contratuais do Segurado, lucro cessante e/ou prejuízos por paralisação das atividades.",
        "4.14- As perdas que, direta ou indiretamente, forem originadas em consequência de guerra, invasão, atos de inimigos estrangeiros; hostilidades e operações bélicas, com ou sem declaração de guerra, guerra civil, rebelião, revolução, insurreição, revoltas, motins ou que as leis classificam como delitos contra a segurança interna do Estado.",
        "4.15- Não obstante o que em contrário possam dispor as condições gerais, especiais e/ou particulares do presente seguro, fica entendido e concordado que, para efeito inventário, não estarão cobertos danos e perdas causados direta ou indiretamente por ato terrorista, cabendo a Seguradora comprovar com documentação hábil, acompanhada de laudo circunstanciado que caracterize a natureza do atentado, independentemente de seu propósito, e desde que este tenha sido devidamente reconhecido como atentatório à ordem pública pela autoridade pública competente.",
        "4.16- As perdas causadas ou resultantes de qualquer tipo de poluição ou contaminação, sejam súbitas ou graduais.",
        "4.17- As perdas provenientes direta ou indiretamente de reação nuclear, radiação nuclear ou contaminação radioativa, qualquer que seja a origem que as causem.",
        "4.18- As perdas ocasionadas por ondas sônicas causadas por aviões ou outras aeronaves que voem a velocidade sônica ou supersônica.",
        "4.19- Atos de autoridades públicas, salvo se para evitar propagação dos riscos cobertos por esta apólice ou certificado de seguro.",
        "4.20- Perdas ocasionadas por implantação ou formação da cultura em zonas ecologicamente inadequadas, ou em terras exploradas sem a adoção de práticas de conservação de solo e fertilidade.",
        "4.21- Adoção de práticas em desacordo com as recomendações técnicas dos órgãos oficiais.",
        "4.22- Queda de cotação dos produtos no mercado.",
        "4.23- Impossibilidade de venda dos produtos no mercado.",
        "4.24- Qualquer perda por ataque cibernético, dano, responsabilidade, custo ou despesa direta ou indiretamente causada por:",
        "4.24.1) uso ou incapacidade de usar qualquer computador, sistema de computador, programa de software de computador, processo computacional ou qualquer outro sistema  eletrônico;",
        "4.24.2) qualquer vírus de computador ou código malicioso;",
        '4.24.3) qualquer fraude relacionada a computador relacionado aos itens "4.24.1" e/ou "4.24.2" acima.',
        "4.25- Riscos associados à violação, ou potencial violação, pelo Segurado e/ou eventuais sócios ou acionistas, diretores, empregados, agentes prepostos, e outras pessoas que venham a agir em seu nome, direta e indiretamente, dos direitos humanos, incluindo, mas não se limitando, a qualquer forma de abuso humano, servidão, trabalho forçado, trabalho compulsório, tráfico humano ou escravidão em suas atividades comerciais.",
    ]
    return "\n".join(excluded_risks_information)
