@baseUrl = http://uatplug.essor.net
### Transmit
POST {{baseUrl}}/authentication-system/v1/users
Authorization: Bearer QyJhbGciOiJIUzI1NiIsInR5TxI2IkpXVzJ9
# Accept: application/json
Content-Type: application/json

{
    "email": "cristovam.lage4@essor.com.br",
    "phone_number": "+5551993182697",
    "name": "Cristovam Lage"
}