### Get token
GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://storage.azure.com/
Metadata: true

> {% client.global.set("token", response.body.access_token); %}

###

### List blobs
GET https://absuatstagronext.blob.core.windows.net/repository?restype=container&comp=list
Authorization: Bearer {{token}}
x-ms-version: 2023-11-03