@baseUrl = http://uatplug.essor.net
### Transmit
POST {{baseUrl}}/authentication-system/v1/users
Accept: application/json
Authorization: Bearer XXU2YDUcRhxJqXWwPkMyW7JA5Kba3T1CIj9EZo6S4d44a7ce
Content-Type: application/json

{
    "email": "raul.regadas@essor.com.br",
    "phone_number": "+5551994227117",
    "name": "Raul Regadas",
}
