"""
Modern Python SDK for Zendesk API.

This package provides a clean, async-first interface to the Zendesk API
with full type safety and comprehensive error handling.
"""

__version__ = "0.17.0"

from .client import ZendeskClient
from .clients import (
    ArticlesClient,
    AttachmentsClient,
    AuditsClient,
    AutomationsClient,
    BrandsClient,
    CategoriesClient,
    CommentsClient,
    CustomStatusesClient,
    GroupsClient,
    HelpCenterClient,
    IncrementalClient,
    JobStatusesClient,
    OrganizationsClient,
    SearchClient,
    SectionsClient,
    SlaPoliciesClient,
    TagsClient,
    TicketFieldsClient,
    TicketFormsClient,
    TicketMetricsClient,
    TicketsClient,
    TriggersClient,
    UsersClient,
    ViewsClient,
    WebhooksClient,
)
from .config import CacheConfig, ZendeskConfig
from .exceptions import (
    ZendeskAuthException,
    ZendeskBaseException,
    ZendeskHTTPException,
    ZendeskPaginationException,
    ZendeskRateLimitException,
    ZendeskTimeoutException,
    ZendeskValidationException,
)
from .models import (
    Article,
    Audit,
    Automation,
    Brand,
    Category,
    CustomStatus,
    EnrichedTicket,
    Group,
    GroupMembership,
    JobStatus,
    PasswordRequirements,
    SearchQueryConfig,
    SearchType,
    Section,
    SlaPolicy,
    SortOrder,
    TicketChannel,
    TicketField,
    TicketForm,
    TicketMetrics,
    TicketPriority,
    TicketPriorityInput,
    TicketStatus,
    TicketStatusInput,
    TicketType,
    TicketTypeInput,
    Trigger,
    UserRole,
    View,
    ViewCount,
    Webhook,
)

__all__ = [
    # Main client
    "ZendeskClient",
    "ZendeskConfig",
    "CacheConfig",
    # Resource clients
    "UsersClient",
    "GroupsClient",
    "OrganizationsClient",
    "TicketsClient",
    "TicketFieldsClient",
    "TicketFormsClient",
    "TicketMetricsClient",
    "JobStatusesClient",
    "CustomStatusesClient",
    "TriggersClient",
    "AutomationsClient",
    "WebhooksClient",
    "SlaPoliciesClient",
    "IncrementalClient",
    "BrandsClient",
    "CommentsClient",
    "TagsClient",
    "AuditsClient",
    "AttachmentsClient",
    "SearchClient",
    "ViewsClient",
    # Help Center
    "HelpCenterClient",
    "CategoriesClient",
    "SectionsClient",
    "ArticlesClient",
    # Models
    "Group",
    "GroupMembership",
    "EnrichedTicket",
    "TicketField",
    "TicketForm",
    "TicketMetrics",
    "JobStatus",
    "CustomStatus",
    "Trigger",
    "Automation",
    "Webhook",
    "SlaPolicy",
    "Brand",
    "Audit",
    "Category",
    "Section",
    "Article",
    "View",
    "ViewCount",
    # Search
    "SearchQueryConfig",
    "SearchType",
    "TicketStatus",
    "TicketStatusInput",
    "TicketPriority",
    "TicketPriorityInput",
    "TicketType",
    "TicketTypeInput",
    "TicketChannel",
    "UserRole",
    "SortOrder",
    # Exceptions
    "ZendeskBaseException",
    "ZendeskHTTPException",
    "ZendeskAuthException",
    "ZendeskRateLimitException",
    "ZendeskPaginationException",
    "ZendeskTimeoutException",
    "ZendeskValidationException",
    # User models
    "PasswordRequirements",
]
